version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins # Use Jenkins-specific Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Ensure Docker client uses socket
volumes:
  jenkins_home:
